apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipchat-frontend
  labels:
    app: zipchat
    component: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: zipchat
      component: frontend
  template:
    metadata:
      labels:
        app: zipchat
        component: frontend
    spec:
      containers:
        - name: frontend
          image: zipchat-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: '50m'
              memory: '128Mi'
            limits:
              cpu: '200m'
              memory: '256Mi'
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          securityContext:
            runAsNonRoot: true
            runAsUser: 101
            runAsGroup: 101
---
apiVersion: v1
kind: Service
metadata:
  name: zipchat-frontend
  labels:
    app: zipchat
    component: frontend
spec:
  selector:
    app: zipchat
    component: frontend
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zipchat-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/proxy-body-size: '8m'
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: zipchat-frontend
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: zipchat-backend
                port:
                  number: 80
