apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: zipchat-backend-hpa
  labels:
    app: zipchat
    component: backend
  annotations:
    prometheus.io/scrape: 'true'
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: zipchat-backend
  minReplicas: 3
  maxReplicas: 10
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Pods
          value: 2
          periodSeconds: 60
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
    - type: External
      external:
        metric:
          name: http_requests_total
          selector:
            matchLabels:
              app: zipchat
              component: backend
        target:
          type: AverageValue
          averageValue: 1000
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: zipchat-frontend-hpa
  labels:
    app: zipchat
    component: frontend
  annotations:
    prometheus.io/scrape: 'true'
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: zipchat-frontend
  minReplicas: 3
  maxReplicas: 10
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Pods
          value: 2
          periodSeconds: 60
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
    - type: External
      external:
        metric:
          name: http_requests_total
          selector:
            matchLabels:
              app: zipchat
              component: frontend
        target:
          type: AverageValue
          averageValue: 2000
