apiVersion: batch/v1
kind: CronJob
metadata:
  name: database-backup
  labels:
    app: backup
spec:
  schedule: '0 0 * * *' # Každý den o půlnoci
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: backup
              image: postgres:14-alpine
              command:
                - /bin/sh
                - -c
                - |
                  # Vytvoření zálohy
                  BACKUP_FILE="/backup/backup_$(date +%Y%m%d_%H%M%S).dump"
                  PGPASSWORD=$POSTGRES_PASSWORD pg_dump -h $POSTGRES_HOST -U $POSTGRES_USER -d $POSTGRES_DB -F c -f $BACKUP_FILE

                  # Verifikace zálohy
                  if ! PGPASSWORD=$POSTGRES_PASSWORD pg_restore -l $BACKUP_FILE > /dev/null; then
                    echo "Backup verification failed"
                    exit 1
                  fi

                  # Nahrání do S3
                  aws s3 cp $BACKUP_FILE s3://$S3_BUCKET/backups/

                  # Smazání starých záloh (30 dní)
                  aws s3 ls s3://$S3_BUCKET/backups/ | awk '{print $4}' | while read -r file; do
                    if [[ $(date -d "$(aws s3 ls s3://$S3_BUCKET/backups/$file | awk '{print $1" "$2}')" +%s) -lt $(date -d "30 days ago" +%s) ]]; then
                      aws s3 rm s3://$S3_BUCKET/backups/$file
                    fi
                  done

                  # Smazání lokální zálohy
                  rm -f $BACKUP_FILE

                  # Odeslání notifikace
                  aws sns publish \
                    --topic-arn $SNS_TOPIC_ARN \
                    --subject "Database backup completed" \
                    --message "Backup of $POSTGRES_DB completed successfully at $(date)"
              env:
                - name: POSTGRES_HOST
                  valueFrom:
                    secretKeyRef:
                      name: database-credentials
                      key: host
                - name: POSTGRES_USER
                  valueFrom:
                    secretKeyRef:
                      name: database-credentials
                      key: user
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: database-credentials
                      key: password
                - name: POSTGRES_DB
                  valueFrom:
                    secretKeyRef:
                      name: database-credentials
                      key: database
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: aws-credentials
                      key: access-key
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: aws-credentials
                      key: secret-key
                - name: AWS_DEFAULT_REGION
                  value: eu-central-1
                - name: S3_BUCKET
                  value: zipchat-backups
                - name: SNS_TOPIC_ARN
                  valueFrom:
                    secretKeyRef:
                      name: aws-credentials
                      key: sns-topic-arn
              volumeMounts:
                - name: backup-volume
                  mountPath: /backup
          volumes:
            - name: backup-volume
              emptyDir: {}
          restartPolicy: OnFailure
          backoffLimit: 3
